In [159]:
m = np.array([0,1,0,0,1,0,0,0,0,0,0,0,0,0,0])

In [155]:
def sequential_window_algorithm(y):
    r = len(y)
    outRF = y.copy()
    
    # Making 5 Epoch sliding windows only if there are >= 5 Epochs
    if r>=5:
        c = 0
        for i in range(r-4):
            if outRF[i] == 0 and outRF[i+4] == 0:
                for j in range(i,(i+4)+1):
                    if outRF[j] == 1:
                        c += 1
                if c <= 1:
                    for k in range(i,(i+3)+1):
                        outRF[k] = 0
                c = 0
    
    return outRF
                    
                

In [160]:
sequential_window_algorithm(m)

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [115]:
y

array([1, 0, 1, 0, 1])

In [5]:
import numpy as np

In [20]:
a = np.zeros(3)

a[0:2] = np.array([3,
                   4])

In [12]:
a[0:1]

array([0.])

In [14]:
a

array([3., 4., 0.])

In [15]:
a = np.zeros(3)

In [21]:
a

array([3., 4., 0.])

In [23]:
def generate_names(montages, signals, features):
  """
  Generates a list of names combining montages, signals, and features.

  Args:
    montages: A list of montage names (strings).
    signals: A list of signal names (strings).
    features: A list of feature names (strings).

  Returns:
    A list of strings, each combining a montage, signal, and feature.
  """

  names = []
  for montage in montages:
    for signal in signals:
      for feature in features:
        name = f"{montage}_{signal}_{feature}"
        names.append(name)
  return names

# Example usage
montages = ["M1", "M2", "M3"]
signals = ["ca4","cd4","cd3","cd2","cd1"]
features = ["ll", "skew", "kurt"]

names = generate_names(montages, signals, features)

print(names)

['M1_ca4_ll', 'M1_ca4_skew', 'M1_ca4_kurt', 'M1_cd4_ll', 'M1_cd4_skew', 'M1_cd4_kurt', 'M1_cd3_ll', 'M1_cd3_skew', 'M1_cd3_kurt', 'M1_cd2_ll', 'M1_cd2_skew', 'M1_cd2_kurt', 'M1_cd1_ll', 'M1_cd1_skew', 'M1_cd1_kurt', 'M2_ca4_ll', 'M2_ca4_skew', 'M2_ca4_kurt', 'M2_cd4_ll', 'M2_cd4_skew', 'M2_cd4_kurt', 'M2_cd3_ll', 'M2_cd3_skew', 'M2_cd3_kurt', 'M2_cd2_ll', 'M2_cd2_skew', 'M2_cd2_kurt', 'M2_cd1_ll', 'M2_cd1_skew', 'M2_cd1_kurt', 'M3_ca4_ll', 'M3_ca4_skew', 'M3_ca4_kurt', 'M3_cd4_ll', 'M3_cd4_skew', 'M3_cd4_kurt', 'M3_cd3_ll', 'M3_cd3_skew', 'M3_cd3_kurt', 'M3_cd2_ll', 'M3_cd2_skew', 'M3_cd2_kurt', 'M3_cd1_ll', 'M3_cd1_skew', 'M3_cd1_kurt']


In [28]:
def generate_names(montages, features):
 """
 Generates a list of names combining montages and features.

 Args:
   montages: A list of montage names (strings).
   features: A list of feature names (strings).

 Returns:
   A list of strings, each combining a montage and feature.
 """

 names = []
 for montage in montages:
   for feature in features:
     name = f"{montage}_{feature}"
     names.append(name)
 return names

# Example usage
montages = ["M1", "M2", "M3"]
features = ["ca4_ll", "cd4_ll", "cd3_ll", "cd2_ll", "ca1_ll"]

names = generate_names(montages, features)

print(names)

['M1_ca4_ll', 'M1_cd4_ll', 'M1_cd3_ll', 'M1_cd2_ll', 'M1_ca1_ll', 'M2_ca4_ll', 'M2_cd4_ll', 'M2_cd3_ll', 'M2_cd2_ll', 'M2_ca1_ll', 'M3_ca4_ll', 'M3_cd4_ll', 'M3_cd3_ll', 'M3_cd2_ll', 'M3_ca1_ll']
